# Generated by Django 5.0.2 on 2024-03-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
