# Generated by Django 5.0.2 on 2024-03-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_songs',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='Music.songs'),
        ),
    ]
